### ISSUE TITLE
Implement imports

### ISSUE THREAD

**Issue by kriskowal** [uber/thriftify#20]

**Comment by GREENpoint** [comment]
Hi, guys! We need this feature for our team. What status of this issue?

**Comment by kriskowal** [comment]
@GREENpoint I just completed a reimplementation of Thriftify that is more closely tied to [ThriftRW][], since it implements custom reader/writer instances and constructors for each Thrift IDL struct, and bypasses the intermediate object format for performance reasons. So, look to ThriftRW directly for new features hereafter.

As for imports, they are not on our roadmap yet since we can get by without them. To implement imports, we need to support both sync and async dependency analysis and thread the API through TChannel very differently.

Contributions are, however, very welcome and we would be glad to provide guidance and review for this work. Otherwise, make a case for the feature and we can adjust and let you know where it fits on our roadmap.

cc stakeholders @abhinav @blampe @jcorbin @leizha 

[ThriftRW]: https://github.com/uber/thriftrw

**Comment by s-panferov** [comment]
@kriskowal on which branch we should base our work? There is https://github.com/uber/thriftify/pull/23, but it seems incompleted and there is no progress for a long time.

**Comment by s-panferov** [comment]
@kriskowal ah, I see, https://github.com/uber/thriftrw/pull/15. Thanks!

**Comment by kriskowal** [comment]
Please open an issue on ThriftRW to track this issue if you need further assistance. ThriftRW now has feature parity with Thriftify and is integrated in TChannel master.
